### ISSUE TITLE
Companion object cover method "tupled" in case class

### ISSUE THREAD

**Issue by mgosk** [VirtusLab/unicorn#11]
I trying to migrate slick from 1.0 to 2.0 and unicorn to 0.6, but I have small problem.

Examply I have tree classes:

``` scala
case class User(id: Option[UserId],
                login: String
                 ) extends WithId[UserId]

object User {
  val form = Form(
    mapping(
      "id" -> optional(longNumber.transform((number: Long) => UserId(number), (userId: UserId) => userId.id)),
      "login" -> nonEmptyText(4)
    ) (User.apply)(User.safeUnapply)
  )
}

class Users(tag: Tag) extends IdTable[UserId, User](tag,"users") {
  def login = column[String]("login")
  def * = (id.? ,login) <> (User.tupled, User.unapply )
}
```

During compilation I get following error  "value tupled is not a member of object model.User"
It looks that is related with unexpected compiler behavior.
https://issues.scala-lang.org/browse/SI-3664

Do You have any workaround for this bug, another from changing objects names.

**Comment by splodingsocks** [comment]
Or, in the companion object you can do this:

```scala
object User {
  // Other code...
  val tupled = (this.apply _).tupled
}
```
