### ISSUE TITLE
Can I have uppercase ID column name in SQL queries?

### ISSUE THREAD

**Issue by dante4d** [VirtusLab/unicorn#31]
I'm working on refactoring my Play app from Anorm to Slick and want to use unicorn 0.6.0-M8. I'm using H2 database that is case sensitive and all my ID column names are uppercase, so I get exceptions because of lowercase ID column name used by unicorn, like such:

```
[JdbcSQLException: Column "X2.id" not found; SQL statement:
select x2."NAME", x2."ADDRESS", x2."CONTACT", x2."EMAIL", x2."PHONE", x2."id" from "CUSTOMERS" x2 [42122-175]]
```

Here's my current test code:

``` scala
case class CustomerId(id: Long) extends AnyVal with BaseId

case class CustomerRow(name: String,
                       address: String,
                       contact: String,
                       email: String,
                       phone: String,
                       id: Option[CustomerId] = None) extends WithId[CustomerId] with RowModel {
  override def key = id.get.id
  override def data = List(id, name, address, contact, email, phone)
  override def save(id: Option[Long] = None)(implicit user: User) = id match {
    case Some(i) => {
      play.api.Logger.debug(id.toString)
      Customer.update(this.copy(id = Some(CustomerId(i))))
    }
    case None => Customer.insert(this)
  }
  override def toString = name
}

class CustomersTable(tag: Tag) extends IdTable[CustomerId, CustomerRow](tag, "CUSTOMERS") {
  def name = column[String]("NAME", O.NotNull)
  def address = column[String]("ADDRESS", O.NotNull)
  def contact = column[String]("CONTACT", O.NotNull)
  def email = column[String]("EMAIL", O.NotNull)
  def phone = column[String]("PHONE", O.NotNull)
  override def * = (name, address, contact, email, phone, id.?) <> (CustomerRow.tupled, CustomerRow.unapply)
}

object CustomerRepository extends BaseIdRepository[CustomerId, CustomerRow, CustomersTable](TableQuery[CustomersTable])
```

And here's how I'm using it:

``` scala
  def list: Seq[CustomerRow] = {
    DB.withSession { implicit session =>
      CustomerRepository.findAll sortWith {
        _.name.toLowerCase < _.name.toLowerCase
      }
    }
  }

  def findById(id: Long): Option[CustomerRow] = {
    DB.withSession { implicit session =>
      CustomerRepository.findById(CustomerId(id))
    }
  }
```

The **id** method in class [IdTable](https://github.com/VirtusLab/unicorn/blob/v0.6.x-slick-2.1.x/unicorn-core/src/main/scala/org/virtuslab/unicorn/Tables.scala) is declared final so I can't override it in my classes:

``` scala
/** @return id column representation of this table */
final def id = column[Id]("id", O.PrimaryKey, O.AutoInc)
```

I guess that's where the exceptions come from. I tried making my own ID method, but that only solves the **findAll** method, inserts/updates/deletes still use the lowercase one:

``` scala
def ID = column[CustomerId]("ID", O.PrimaryKey, O.AutoInc)
override def * = (name, address, contact, email, phone, ID.?) <> (CustomerRow.tupled, CustomerRow.unapply)
```

How can I get around this and make unicorn use an uppercase ID column name?? I mean if there's way without using my own patch/build of unicorn with "ID" or any Slick hack's to change the SQL strings?? I'm quite new to Scala/Play/Slick so I might be missing something very obvious here...

**Comment by jarl-dk** [comment]
The feature
```scala
  override val idColumnName = "ID"
```
Should really be documented.

You may also consider making "ID" the default, since many new developers are starting out with H2.

**Comment by Kwestor** [comment]
@jarl-dk Thanks for feedback, I'll document this one.

As for changing default value - we didn't want to introduce breaking change back then, I'll think about it.

**Comment by jarl-dk** [comment]
Now that I think about it: My opinion is that default should be down case.

My proposal was to get newcomers faster up and running, but chaning the default in Unicorn is not the right approach.

A better approach would be to change the the H2 to uppercase all table and column names so the programmer does not need to do it...

But definitely the documention would help in the readme.

**Comment by jarl-dk** [comment]
The examples in the README.md is somehow written towards H2 driver (H2 is mention in an example, and all the names are written in capital), so a line like
```scala
override val idColumnName = "ID" //name of id column, default is 'id', but H2 requires it to be uppercase
```
Would make so much sense along the other column definitions

**Comment by Kwestor** [comment]
See #48, I've added an info about this field.
