### ISSUE TITLE
Introduce sbt-release

### ISSUE THREAD

**Issue by bambuchaAdm** [VirtusLab/unicorn#41]
To reduce overhead to make release - https://github.com/sbt/sbt-release

**Comment by Kwestor** [comment]
@bambuchaAdm I've added `sbt-release` and released `0.6.3` as a test - nothing really changed since `0.6.2`.

Short info is added into [contribution guide](https://github.com/VirtusLab/unicorn/blob/v0.6.x-slick-2.1.x/CONTRIBUTING.md#releasing).
