### ISSUE TITLE
HList support

### ISSUE THREAD

**Issue by mgosk** [VirtusLab/unicorn#47]
Does Unicorn support HLists in Slick ?

http://stackoverflow.com/questions/20555304/how-can-i-use-the-new-slick-2-0-hlist-to-overcome-22-column-limit

**Comment by Kwestor** [comment]
We had no use case for them yet, but if you want to check it out and possibly contribute a solution we can provide some help.

**Comment by mgosk** [comment]
I wanted to use tables with more than 22 columns, but if unicorn doesent support it i just split table.

**Comment by cvogt** [comment]
or use a nested tuple :)! Not sure if unicorn supports that

**Comment by JakubSroka** [comment]
This feature won't be supported
