### ISSUE TITLE
Is this the correct way to do queries?

### ISSUE THREAD

**Issue by Ir1sh** [VirtusLab/unicorn#49]
Please see this gist. https://gist.github.com/Ir1sh/d555e58edf654fe74752

Am I doing something wrong that makes me have to have a return type of Option[Socs#TableElementType] and Query[Socs, Socs#TableElementType, Seq]?

Intellij also tells me that it cannot resolve symbol id and === on line 47 of Soc.scala and line 27 of SocsRepository respectively

And finally adding foreignKeys in the Socs class as commented out in the gist gives me 'cannot resolve symbol' on that _.id but all of a sudden intellij can resolve the two symbols mentioned above.

Could you add an example of declaring foreign keys with play slick to the docs?

Sorry for asking for support instead of otherwise contributing but I am only learning scala / play / slick etc and getting confused

**Comment by Kwestor** [comment]
I'll look into that and clarify documentation where possible, thanks for reporting this problem.

**Comment by Ir1sh** [comment]
Thanks if it helps, changing the name of repository class fixes the cannot resolves in Soc,scala but then I get cannot resolve for Socs#TableElementType in the repository class.  It is probably something I am doing but no idea what

**Comment by Kwestor** [comment]
Ok, sorry it took this long.

For foreign keys we usually use something like this:

```scala
import org.virtuslab.unicorn.LongUnicornPlay._
import org.virtuslab.unicorn.LongUnicornPlay.driver.simple._
import play.api.db.slick.DB
import play.api.Play.current

import scala.slick.lifted.{TableQuery, Tag}

case class CofeeId(id: Long) extends AnyVal with BaseId

object CofeeId extends IdCompanion[CofeeId]

case class Cofee(id: Option[CofeeId],
                 title: String,
                 supplierId: SupplierId) extends WithId[CofeeId]

class Coffes(tag: Tag) extends IdTable[CofeeId, Cofee](tag, "Cofees") {
  def name = column[String]("name")
  def supplierId = column[SupplierId]("supplierId")
  def supplier = foreignKey("supplierId", supplierId, Suppliers.tableQuery)(_.id)
  def * = (id.?, name, supplierId) <>(Cofee.tupled, Cofee.unapply)
}

object Coffes {
  val tableQuery = TableQuery[Coffes]
}

class CofeeRepository extends BaseIdRepository[CofeeId, Cofee, Coffes](Coffes.tableQuery) {
  def getByName(name: String): Option[Cofee] = DB.withSession { implicit session =>
    query.filter(_.name === name).firstOption
  }

  def getBySupplier(supplierId: SupplierId): Seq[Cofee] =
    DB.withSession { implicit session =>
      (for {
        cofee <- Coffes.tableQuery
        if cofee.supplierId === supplierId
      } yield cofee).run
    }
}

case class SupplierId(id: Long) extends AnyVal with BaseId

case object SupplierId extends IdCompanion[SupplierId]

case class Supplier(id: Option[SupplierId], name: String) extends WithId[SupplierId]

class Suppliers(tag: Tag) extends IdTable[SupplierId, Supplier](tag, "Ashes") {
  def name = column[String]("name")

  def * = (id.?, name) <>(Supplier.tupled, Supplier.unapply)
}

object Suppliers {
  val tableQuery = TableQuery[Suppliers]
}

class SuppliersRepository extends BaseIdRepository[SupplierId, Supplier, Suppliers](Suppliers.tableQuery)
```

As you can see, no need to use `TableElementType` anywhere, just use your domain type and everything should work.

As for Intellij - Slick uses some pretty damn hard tricks to make this code compile and sometimes IDE does not catch up with it - it's normal unfortunately. Sometimes if you use `File -> Invalidate caches \ Restart` it fixes problem, but sometimes not, one have to live with it. If sbt / compilation in IDE (`F9` by default in Intellij) says everything is ok, then it's just an IDE quirk.

If you have any further questions, feel free to re-open this issue.
