### ISSUE TITLE
Weird error extending BaseIdRepository with Intellij

### ISSUE THREAD

**Issue by jvican** [VirtusLab/unicorn#55]
Hi everyone,
I'm experiencing a very weird error and, to be honest, I don't have any clue of why. Suppose I have a Container class properly defined:
```scala
case class ContainerId(id: Long) extends AnyVal with BaseId
object ContainerId extends IdCompanion[ContainerId]
case class Container(id: ContainerId) extends WithId[ContainerId]

trait DriverComponent extends LongUnicornCore with HasJdbcDriver

trait ContainerComponent {
  this: DriverComponent =>
  
  class Containers(tag: Tag) extends IdTable[ContainerId, Container](tag, "CONTAINERS") {
    // fields and projection
  }

  class ContainerRepository(query: TableQuery[Container]) extends BaseIdRepository[ContainerId, Container, Containers](query) {
    def all(implicit session: Session): Seq[Container] = query.list
  }
}
```

To me, it seems ok. However, where I get an error in the function 'all'. It says that "Expresion of type List[Containers#TableElementType] doesn't conform to expected type Seq[Container]". If I don't specify the return type of the method is ok.

Do you guys have experience any similar error like this? Am I doing anything wrong?

**Comment by Kwestor** [comment]
Do you have this error also during compilation, or only as red marker in IntelliJ editor tab?

**Comment by jvican** [comment]
Yeah, I know it, I simplified the example. It's not an issue with all, it's an issue with whatever function that returns explicit type. 
Nonetheless, it's already solved. I've invalidated caches and restarted Intellij. Now the error has disappeared. Thanks.

**Comment by Kwestor** [comment]
IntelliJ uses it's own presentation compiler for marking errors in Scala code, and this presentation compiler is often confused by a code with a lot of type-magic and implicits, like Slick or ScalaTest.
