### ISSUE TITLE
Support of Slick 3.0.0-RC2 in Unicorn-core?

### ISSUE THREAD

**Issue by jvican** [VirtusLab/unicorn#61]
Does unicorn-core offer support to the latest version of Slick (Mar 27)?

**Comment by jvican** [comment]
I am working on the integration process with Slick. I will have it soon.

**Comment by Kwestor** [comment]
See #45

**Comment by jvican** [comment]
Sorry, but a new version has been released a few days ago. New changes in RC2:
http://slick.typesafe.com/news/2015/03/27/slick-3.0.0-RC2-released.html

**Comment by bambuchaAdm** [comment]
New version will be available in 4 hours.

**Comment by jvican** [comment]
Thanks @bambuchaAdm If you need any help please contact me

**Comment by Kwestor** [comment]
Guys, we don't need an issue for every RC version of Slick. There is an grouped issue for 3.0 and branch that worked for M1.

It will be updated tomorrow, I'm closing this issue, please move further discussion to #45 if needed.
