### ISSUE TITLE
Not Futures as Return types

### ISSUE THREAD

**Issue by jvican** [VirtusLab/unicorn#64]
Hi guys,

I think that the return types of IdRepositories should not be futures but DBIO. The advantage of this is that the actions can be composed. Moreover, the client of the library should choose when to run an action. What do you think about this?

Cheers

**Comment by pbatko** [comment]
Done in #69, released as Unicorn 1.0.0 https://github.com/VirtusLab/unicorn/tree/v1.0.x-slick-3.1.x
