### ISSUE TITLE
Migrate to Play 2.4

### ISSUE THREAD

**Issue by mkljakubowski** [VirtusLab/unicorn#65]
Migrate to Play 2.4
Update all deps except Slick

**Comment by Ir1sh** [comment]
as it stands this project is not compatible with play 2.4.x is that correct?

**Comment by mgilbertnz** [comment]
Unicorn Version 1.0 (the one just released) is compatible with Play 2.4 and Slick 3.1.  I've been using it in a project with those versions.

**Comment by Ir1sh** [comment]
oh excellent thanks
