### ISSUE TITLE
Guidelines to new version

### ISSUE THREAD

**Issue by javierfvargas** [VirtusLab/unicorn#71]
Where can I see some sample code on how to use the new version, now supporting slick 3.1?

**Comment by pbatko** [comment]
You can find updated code examples on [this branch's](https://github.com/VirtusLab/unicorn/tree/wip/v1.0.0-guide)  README file
They'll be merged into v1.0.x branch after we complete docs update.

**Comment by pbatko** [comment]
Documentation has been updated (#73).
