### ISSUE TITLE
unicorn-play 1.0.0 - O.NotNull

### ISSUE THREAD

**Issue by jirihelmich** [VirtusLab/unicorn#76]
I'm finishing migration of my project from Slick 2.0 to Slick 3.0, Play 2.4 and Unicorn 1.0. I just came up to this:

If I had a definition like
```
def analyzerId = column[AnalyzerTemplateId]("analyzer_id", O.NotNull) 
```
it was OK with previous releases of Slick and Unicorn, but now I get:

`value NotNull is not a member of org.virtuslab.unicorn.LongUnicornPlay.driver.ColumnOptions`

I was digging into it. What I found so far:

- LongUnicornPlay driver should be JdbcProfile, which extends SqlProfile, which has the additional NotNull column option - so far so good
- IdTable -> BaseTable ->  Table = RelationalProfile.super[RelationalTableComponent].Table[T] and SqlProfile -> RelationalProfile, therefore ColumnOptions of Table do not contain NotNull

I'm not 100 % sure this is an issue of Unicorn, but it seems so to me. Can anyone, please, advise?

**Comment by mgilbertnz** [comment]
Hey, haven't had a dig yet - you may well be right.  Just thought I'd point out that explicitly stating O.NotNull isn't usually required, at least not anymore.  This may serve as a work-around to get you going again.

http://slick.typesafe.com/doc/3.1.0/schemas.html
```
NotNull, Nullable
Explicitly mark the column as nullable or non-nullable when creating the DDL statements for the table. Nullability is otherwise determined from the type (Option or non-Option). There is usually no reason to specify these options.```

**Comment by jirihelmich** [comment]
Hi, thanks for the super-quick answer. Will remove NotNulls then. :)
