### ISSUE TITLE
still possible to use types other than long as id?

### ISSUE THREAD

**Issue by Ir1sh** [VirtusLab/unicorn#77]
Is this still possbile with play 2.4 and slick3.1?

When I look at this pr https://github.com/VirtusLab/unicorn/pull/27 it seems like it is /was possible with slick 2.x but when I look at org.virtuslab.unicorn.identifiers I dont see any mappedToBase being imported or used?  Is this no longer necessary in slick 3.1?

When I try to do 

```
case class VisitorSignatureId(id: String) extends AnyVal with BaseId
object VisitorSignatureId extends IdCompanion[VisitorSignatureId] {}
```
I get object creation impossible since member apply(id: underlying): id in PlayIdentifiers.Applicable is not defined on the companion object and when I command hover over BaseId I see MappedTo[Long]

**Comment by bambuchaAdm** [comment]
From where you take `BaseId` trait ? Please send import statement. 

If you try to get BaseId with String as Underlying type you need to "bake" your own cake from Unicorn ingredients.

From fact that most used ID type is Long based, Unicorn [provides Long based baked version](https://github.com/VirtusLab/unicorn/blob/v1.0.x-slick-3.1.x/unicorn-play/src/main/scala/org/virtuslab/unicorn/UnicornPlay.scala#L39). If you want to create String based cake object should look more less like this
```
object StringUnicornPlay extends UnicornPlay[String]
```
and usage like this
```
import StringUnicornPlay._

case class VisitorSignatureId(id: String) extends AnyVal with BaseId
object VisitorSignatureId extends IdCompanion[VisitorSignatureId] {}
```

**Comment by Ir1sh** [comment]
Thank-you very much that makes sense.  Do I need to change anything with WithId or IdCompanion or IdTable because after creating 

`object StringUnicornPlay extends UnicornPlay[String]`

and importing that instead of LongUnicornPlay the errors I mentioned above dissapear but my table class now shows errors

`Error:(36, 51) type arguments [models.VisitorSignatureId,models.VisitorSignature] do not conform to class IdTable's type parameter bounds [Id <: Tables.this.BaseId,Entity <: Tables.this.WithId[Id]]
  class VisitorSignatures(_tableTag: Tag) extends IdTable[VisitorSignatureId, VisitorSignature](
                                                  ^`
and 

`Error:(27, 5) type arguments [models.VisitorSignatureId,models.VisitorSignature,models.VisitorSignatures.VisitorSignatures] do not conform to class BaseIdRepository's type parameter bounds [Id <: IdRepositories.this.BaseId,Entity <: IdRepositories.this.WithId[Id],Table <: IdRepositories.this.IdTable[Id,Entity]]
    BaseIdRepository[VisitorSignatureId, VisitorSignature, VisitorSignatures](VisitorSignatures)
    ^`

**Comment by Ir1sh** [comment]
edit nevermind had to change imports to StringUnicornPlay in all the right places, seems to work like a charm thanks
