### ISSUE TITLE
Remove dependency on Play.current?

### ISSUE THREAD

**Issue by anthonyhoman** [VirtusLab/unicorn#82]
It's very possible I'm overlooking something, but as far as I can tell I can't use the default Guice dependency injection in Play 2.5 with Unicorn.  I have a simple repository which extends from BaseIdRepository, but when I attempt to inject it to a controller I get a "There is no started application" error.  This is due to UnicornPlay.scala, line 16, calling Play.current.  My understanding is that this is now deprecated.

Any chance on removing this dependency on Play.current?

**Comment by liosedhel** [comment]
Unicorn is updated to slick 3.1 but not to play 2.5 yet (currently supported version is play 2.4). Indeed, new play 2.5 force us to remove `Play.current` and apply DI instead. To address this issue we need to redesign some parts of Unicorn. We are currently on it, so stay tuned!

**Comment by mgilbertnz** [comment]
Hi guys,

Perhaps take a look at my pull-request for one approach to removing Play.current dependency.  I've been successfully using Unicorn with Play 2.5 with this patch.

https://github.com/VirtusLab/unicorn/pull/75

**Comment by anthonyhoman** [comment]
Thanks for the prompt reply liosedhel.  I'll look forward to the upcoming 2.5 support.  And thanks Matt for sharing your approach.

**Comment by liosedhel** [comment]
@mgilbertnz thanks for your effort, it's a nice workaround. I am glad it works also for play 2.5. Still, unicorn depends on play-slick 1.1.0 which is targeted for play 2.4. We plan to migrate unicorn fully to play 2.5 (and to play-slick [2.0.0](https://github.com/playframework/play-slick)) soon.

**Comment by anthonyhoman** [comment]
@liosedhel I'm considering moving my development branch to the pull request branch referenced in this issue.  Do you think this pull request is likely to undergo further changes, or is it fairly safe to start using this with Play 2.5?

**Comment by liosedhel** [comment]
@anthonyhoman I am currently working on unicorn activator template update to verify usability of unicorn 1.1. You can see required changes in Play project here: https://github.com/liosedhel/activator-play-advanced-slick/tree/liosedhel/update-to-unicorn-1.1. You can check if this will work for you - I will be grateful for all the comments. It seems to be fairly safe for using.

**Comment by anthonyhoman** [comment]
@liosedhel Thanks liosedhel.  I've installed your updated 1.1 feature branch locally and so far it is working great with my Play 2.5 app.  I'll report issues if I find any.

**Comment by mgilbertnz** [comment]
Hi guys, how's progress on getting a release without a dependency on Play.current?  Let me know if there is anything I can do to help.

Matt
