### ISSUE TITLE
no implementation for slick.basic.DatabaseConfig was bound

### ISSUE THREAD

**Issue by MarkRBM** [VirtusLab/unicorn#96]
hi,

using unicorn-core and unicorn-play 1.3.2, play 2.6, play-slick 3.0.1 and slick 3.2.3 I get a guice injection error at start up saying `No Implementation for slick.basic.DatabaseConfig<slick.jdbc.JdbcProfile>`

I was getting this thrown from my own code but I have refactored all occurences of that dependency to  be slick.backend.DatabaseConfig and now I seem to be getting it from Unicorn-play code and I think its originating from here https://github.com/VirtusLab/unicorn/blob/cb1ccb0585ef1020f752afc508dd9224870d5c4e/unicorn-play/src/main/scala/org/virtuslab/unicorn/UnicornPlay.scala#L10

should this work or do these references need to be refactored to slick.backend.DatabaseConfig?

**Comment by MarkRBM** [comment]
any thoughts at all?

**Comment by bartosz822** [comment]
Hi, sorry for long response. `slick.backend.DatabaseConfig` is deprecated in slick 3.2 and `slick.basic.DatabaseConfig` is what you should be using in your whole app. Also `slick.backend.DatabaseConfig` is implemented like that:
```val DatabaseConfig = slick.basic.DatabaseConfig```
 so changing imports is probably not a problem here.

 I am guessing that you are using `LongUnicornPlay` in place where `LongUnicornPlayJDBC` should be used.

**Comment by MarkRBM** [comment]
Thank-you for the response, I think I just got mixed up on which one was decorated .

I am using slick.basic.DatabaseConfig in the way shown here https://github.com/VirtusLab/unicorn#play-example and it is when it tries to inject it into that class that I get the no implementation for x error I mentioned.

any ideas on why that would be happening?

**Comment by MarkRBM** [comment]
oh I think maybe your readme is out of date and how to inject dbConf has changed in play and that is probably my issue

**Comment by bartosz822** [comment]
Oh we forgot to update this part, you should inject `DatabaseConfigProvider`  and then use it to get dbonf (`databaseConfigProvider.get[JdbcProfile]`)
